CREATE DATABASE IF NOT EXISTS wfu_eye_db;
USE wfu_eye_db;
-- Script was generated by Devart Entity Developer, Version 5.7.576.0
-- Script date 5/04/2015 12:48:04 AM
-- Target Server: MySQL
-- Server Version: 5.6

SET foreign_key_checks = 0;
-- 
-- Dropping a table wfu_eye_db.DeviceHistories 
-- 
DROP TABLE IF EXISTS wfu_eye_db.DeviceHistories;

-- 
-- Dropping a table wfu_eye_db.Devices 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Devices;

-- 
-- Dropping a table wfu_eye_db.ArchivedWaypointResponders 
-- 
DROP TABLE IF EXISTS wfu_eye_db.ArchivedWaypointResponders;

-- 
-- Dropping a table wfu_eye_db.Waypoints 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Waypoints;

-- 
-- Dropping a table wfu_eye_db.Nodes 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Nodes;

-- 
-- Dropping a table wfu_eye_db.NodeLinks 
-- 
DROP TABLE IF EXISTS wfu_eye_db.NodeLinks;

-- 
-- Dropping a table wfu_eye_db.Users 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Users;

SET foreign_key_checks = 1;
-- 
-- Creating a table wfu_eye_db.Nodes 
-- 
CREATE TABLE wfu_eye_db.Nodes (
   ID INTEGER UNSIGNED NOT NULL,
   Created BIGINT UNSIGNED NOT NULL,
   LastUpdated BIGINT UNSIGNED NOT NULL,
   Active BIT NOT NULL DEFAULT 0,
   MeshPoint BIT NULL,
   AccessPoint BIT NULL,
   GPSD BIT NULL,
   SatelliteCount INTEGER UNSIGNED NULL,
   MockLocation BIT NULL,
   FakeGPS BIT NULL,
   Number INTEGER UNSIGNED NULL DEFAULT 0,
   Latitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Accuracy DOUBLE NULL,
   Voltage DOUBLE NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table wfu_eye_db.Users 
-- 
CREATE TABLE wfu_eye_db.Users (
   ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
   NameFirst VARCHAR(32) NOT NULL,
   NameMiddle VARCHAR(32) NOT NULL,
   NameLast VARCHAR(32) NOT NULL,
   Type VARCHAR(32) NOT NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table wfu_eye_db.Waypoints 
-- 
CREATE TABLE wfu_eye_db.Waypoints (
   ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
   Created BIGINT UNSIGNED NOT NULL,
   Type VARCHAR(32) NOT NULL,
   Severity INT(9) NOT NULL DEFAULT 0,
   Code INT(9) NOT NULL DEFAULT 0,
   Description TEXT NOT NULL,
   Category VARCHAR(32) NOT NULL,
   Latitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   NextWaypointID INTEGER UNSIGNED NULL,
   ReportedByID INTEGER UNSIGNED NULL,
   Archived TINYINT(1) NOT NULL DEFAULT 0,
   ArchivedTime BIGINT UNSIGNED NULL,
   PRIMARY KEY (ID),
   CONSTRAINT FK_Waypoints_ReportingUser FOREIGN KEY (ReportedByID) REFERENCES wfu_eye_db.Users (ID) ON DELETE SET NULL,
   CONSTRAINT FK_Waypoints_NextWaypoint FOREIGN KEY (NextWaypointID) REFERENCES wfu_eye_db.Waypoints (ID) ON DELETE SET NULL
);

-- 
-- Creating a table wfu_eye_db.NodeLinks 
-- 
CREATE TABLE wfu_eye_db.NodeLinks (
   StartNodeID INTEGER UNSIGNED NOT NULL,
   EndNodeID INTEGER UNSIGNED NOT NULL,
   Active BIT NOT NULL DEFAULT 0,
   SignalStrength DOUBLE NULL,
   LinkSpeed DOUBLE NULL,
   PRIMARY KEY (StartNodeID, EndNodeID),
   CONSTRAINT FK_NodeLinks_Start FOREIGN KEY (StartNodeID) REFERENCES wfu_eye_db.Nodes (ID) ON DELETE CASCADE,
   CONSTRAINT FK_NodeLinks_End FOREIGN KEY (EndNodeID) REFERENCES wfu_eye_db.Nodes (ID) ON DELETE CASCADE
);

-- 
-- Creating a table wfu_eye_db.ArchivedWaypointResponders 
-- 
CREATE TABLE wfu_eye_db.ArchivedWaypointResponders (
   WaypointID INTEGER UNSIGNED NOT NULL,
   UserID INTEGER UNSIGNED NOT NULL,
   PRIMARY KEY (WaypointID, UserID),
   CONSTRAINT FK_ArchivedWaypointResponders_Waypoints FOREIGN KEY (WaypointID) REFERENCES wfu_eye_db.Waypoints (ID),
   CONSTRAINT FK_ArchivedWaypointResponders_Users FOREIGN KEY (UserID) REFERENCES wfu_eye_db.Users (ID)
);

-- 
-- Creating a table wfu_eye_db.Devices 
-- 
CREATE TABLE wfu_eye_db.Devices (
   ID INTEGER UNSIGNED NOT NULL,
   Created BIGINT UNSIGNED NOT NULL,
   LastUpdated BIGINT UNSIGNED NOT NULL,
   Active BIT NOT NULL DEFAULT 0,
   Type VARCHAR(32) NOT NULL DEFAULT 'PHO',
   GPSEnabled BIT NULL,
   GPSHasFix BIT NULL,
   Latitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   Accuracy DOUBLE NULL,
   Humidity DOUBLE NULL,
   AirPressure DOUBLE NULL,
   Temperature DOUBLE NULL,
   LightLevel DOUBLE NULL,
   Charging TINYINT(1) NULL DEFAULT 0,
   BatteryLevel DOUBLE NULL,
   WaypointID INTEGER UNSIGNED NULL,
   UserID INTEGER UNSIGNED NULL,
   NodeID INTEGER UNSIGNED NULL,
   PRIMARY KEY (ID),
   CONSTRAINT FK_Devices_AssignedWaypoint FOREIGN KEY (WaypointID) REFERENCES wfu_eye_db.Waypoints (ID) ON DELETE SET NULL,
   CONSTRAINT FK_Devices_User FOREIGN KEY (UserID) REFERENCES wfu_eye_db.Users (ID) ON DELETE SET NULL,
   CONSTRAINT FK_Devices_Node FOREIGN KEY (NodeID) REFERENCES wfu_eye_db.Nodes (ID) ON DELETE SET NULL
);

-- 
-- Creating a table wfu_eye_db.DeviceHistories 
-- 
CREATE TABLE wfu_eye_db.DeviceHistories (
   DeviceID INTEGER UNSIGNED NOT NULL,
   Created BIGINT UNSIGNED NOT NULL,
   Latitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   Accuracy DOUBLE NULL,
   Humidity DOUBLE NULL,
   AirPressure DOUBLE NULL,
   Temperature DOUBLE NULL,
   LightLevel DOUBLE NULL,
   UserID INTEGER UNSIGNED NULL,
   PRIMARY KEY (DeviceID, Created),
   CONSTRAINT FK_DeviceHistories_Device FOREIGN KEY (DeviceID) REFERENCES wfu_eye_db.Devices (ID) ON DELETE CASCADE,
   CONSTRAINT FK_DeviceHistories_User FOREIGN KEY (UserID) REFERENCES wfu_eye_db.Users (ID) ON DELETE CASCADE
);

