CREATE DATABASE IF NOT EXISTS wfu_eye_db;
USE wfu_eye_db;
-- Script was generated by Devart Entity Developer, Version 5.7.490.0
-- Script date 4/12/2014 3:35:12 AM
-- Target Server: MySQL
-- Server Version: 5.6

SET foreign_key_checks = 0;
-- 
-- Dropping a table wfu_eye_db.DeviceHistories 
-- 
DROP TABLE IF EXISTS wfu_eye_db.DeviceHistories;

-- 
-- Dropping a table wfu_eye_db.Devices 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Devices;

-- 
-- Dropping a table wfu_eye_db.ArchivedWaypointResponders 
-- 
DROP TABLE IF EXISTS wfu_eye_db.ArchivedWaypointResponders;

-- 
-- Dropping a table wfu_eye_db.Waypoints 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Waypoints;

-- 
-- Dropping a table wfu_eye_db.Nodes 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Nodes;

-- 
-- Dropping a table wfu_eye_db.Users 
-- 
DROP TABLE IF EXISTS wfu_eye_db.Users;

SET foreign_key_checks = 1;
-- 
-- Creating a table wfu_eye_db.Nodes 
-- 
CREATE TABLE wfu_eye_db.Nodes (
   ID BIGINT NOT NULL,
   Created BIGINT NOT NULL,
   Updated BIGINT NOT NULL,
   Number BIGINT NULL,
   Latitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   Accuracy DOUBLE NULL,
   Voltage DOUBLE NULL,
   IPAddress BIGINT NULL DEFAULT 0,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table wfu_eye_db.Users 
-- 
CREATE TABLE wfu_eye_db.Users (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   NameFirst VARCHAR(32) NOT NULL,
   NameMiddle VARCHAR(32) NOT NULL,
   NameLast VARCHAR(32) NOT NULL,
   Type VARCHAR(32) NOT NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table wfu_eye_db.Waypoints 
-- 
CREATE TABLE wfu_eye_db.Waypoints (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   Created BIGINT NOT NULL,
   Type VARCHAR(32) NOT NULL,
   Severity INT(9) NOT NULL DEFAULT 0,
   Code INT(9) NOT NULL DEFAULT 0,
   Description TEXT NOT NULL,
   Category VARCHAR(32) NOT NULL,
   Latitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   NextWaypointID BIGINT NULL,
   ReportedByID BIGINT NULL,
   Archived TINYINT(1) NOT NULL DEFAULT 0,
   ArchivedTime BIGINT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT FK_Waypoints_ReportingUser FOREIGN KEY (ReportedByID) REFERENCES wfu_eye_db.Users (ID) ON DELETE SET NULL,
   CONSTRAINT FK_Waypoints_NextWaypoint FOREIGN KEY (NextWaypointID) REFERENCES wfu_eye_db.Waypoints (ID) ON DELETE SET NULL
);

-- 
-- Creating a table wfu_eye_db.Devices 
-- 
CREATE TABLE wfu_eye_db.Devices (
   ID BIGINT NOT NULL,
   Created BIGINT NOT NULL,
   Updated BIGINT NOT NULL,
   Type VARCHAR(32) NOT NULL DEFAULT 'PHO',
   Latitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   Accuracy DOUBLE NULL,
   Humidity DOUBLE NULL,
   AirPressure DOUBLE NULL,
   Temperature DOUBLE NULL,
   LightLevel DOUBLE NULL,
   Charging TINYINT(1) NULL DEFAULT 0,
   BatteryLevel DOUBLE NULL,
   IPAddress BIGINT NULL DEFAULT 0,
   WaypointID BIGINT NULL,
   UserID BIGINT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT FK_Devices_AssignedWaypoint FOREIGN KEY (WaypointID) REFERENCES wfu_eye_db.Waypoints (ID) ON DELETE SET NULL,
   CONSTRAINT FK_Devices_User FOREIGN KEY (UserID) REFERENCES wfu_eye_db.Users (ID) ON DELETE SET NULL
);

-- 
-- Creating a table wfu_eye_db.ArchivedWaypointResponders 
-- 
CREATE TABLE wfu_eye_db.ArchivedWaypointResponders (
   WaypointID BIGINT NOT NULL,
   UserID BIGINT NOT NULL,
   PRIMARY KEY (WaypointID, UserID),
   CONSTRAINT FK_ArchivedWaypointResponders_Waypoints FOREIGN KEY (WaypointID) REFERENCES wfu_eye_db.Waypoints (ID),
   CONSTRAINT FK_ArchivedWaypointResponders_Users FOREIGN KEY (UserID) REFERENCES wfu_eye_db.Users (ID)
);

-- 
-- Creating a table wfu_eye_db.DeviceHistories 
-- 
CREATE TABLE wfu_eye_db.DeviceHistories (
   DeviceID BIGINT NOT NULL,
   Created BIGINT NOT NULL,
   Latitude DOUBLE NULL,
   Longitude DOUBLE NULL,
   Altitude DOUBLE NULL,
   Accuracy DOUBLE NULL,
   Humidity DOUBLE NULL,
   AirPressure DOUBLE NULL,
   Temperature DOUBLE NULL,
   LightLevel DOUBLE NULL,
   UserID BIGINT NULL,
   PRIMARY KEY (DeviceID, Created),
   CONSTRAINT FK_DeviceHistories_Device FOREIGN KEY (DeviceID) REFERENCES wfu_eye_db.Devices (ID) ON DELETE CASCADE,
   CONSTRAINT FK_DeviceHistories_User FOREIGN KEY (DeviceID) REFERENCES wfu_eye_db.Users (ID) ON DELETE CASCADE
);

